spring:
  application:
    name: desafio-itau-backend
  output:
    ansi:
      enabled: ALWAYS

transactions:
  timer:
    seconds: 60

springdoc:
  override-with-generic-response: true

logging:
  file:
    name: app.log

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'